### ISSUE TITLE
Usability as ESP managed component

### ISSUE THREAD

**Issue by mickeyl** [h2zero/esp-nimble-cpp#118]
I tried to use `esp-nimble-cpp` as a managed component by adding it to my `idf_component.yml`, e.g.:

```
dependencies:
  espressif/led_strip: "^2.0.0"
  h2zero/esp-nimble-cpp:
    git: "https://github.com/h2zero/esp-nimble-cpp"
```

After adding a `idf_component.yml` to `esp-nimble-cpp` in its top directory w/ the following contents, it was found:

```
version: "1.5.0"
description: C++ library for the ESP32 NimBLE stack
url: https://github.com/h2zero/esp-nimble-cpp
dependencies:
  idf: ">=5.0"
```

Unfortunately though, I get strange build errors using it that way. Some include files are not found, etc. 
I wonder if anyone else attempted this before?
