### ISSUE TITLE
how to import this component?

### ISSUE THREAD

**Issue by vhp8rc7p** [h2zero/esp-nimble-cpp#220]
i tried to clone this repo and extract it to components folder in my project,it can't find NImBLEDevice.h when i try to build,then i modified idf_component.yml to this:
```
## IDF Component Manager Manifest File
dependencies:
  idf: ">=4.4"
  usb_host_hid: "^1.0.1"
  esp-nimble-cpp:
    override_path: "../components/esp-nimble-cpp"
    version: "*"
```
then when i try to build there are a ton of errors
![image](https://github.com/user-attachments/assets/69869f89-17b5-483f-a865-73e97cc6bd54)
i'm using espidf 5.3.1 and set target to esp32s3,enabled bt in menuconfig,set host to nimble,
i'm new to espidf,any help will be appreciated
